-- 코드를 입력하세요
SELECT  V.MEMBER_NAME
        ,R.REVIEW_TEXT
        ,DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM 
(
    SELECT
            M.MEMBER_ID
            , M.MEMBER_NAME
            , COUNT( M.MEMBER_NAME ) OVER(PARTITION BY M.MEMBER_ID) AS ROW_CNT
    FROM REST_REVIEW R
    INNER JOIN MEMBER_PROFILE M
    ON R.MEMBER_ID = M.MEMBER_ID
    ORDER BY ROW_CNT DESC
    LIMIT 1
    
) V
INNER JOIN REST_REVIEW R
ON R.MEMBER_ID = V.MEMBER_ID
ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT