SELECT 
    YEAR(O.SALES_DATE) AS YEAR
    ,MONTH(O.SALES_DATE) AS MONTH
    ,COUNT(DISTINCT(O.USER_ID)) AS PURCHASED_USERS
    ,ROUND(( COUNT(DISTINCT(O.USER_ID)) / T.CNT),1) AS PUCHASED_RATIO
FROM ONLINE_SALE O
LEFT JOIN USER_INFO U
ON O.USER_ID = U.USER_ID

LEFT JOIN (
        SELECT COUNT(USER_ID) AS CNT FROM USER_INFO
        WHERE YEAR(JOINED) = '2021'
) AS T
ON 1=1
WHERE YEAR(U.JOINED) = '2021'
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH